### ISSUE TITLE
Registry Access Scenarios

### ISSUE THREAD

**Issue by OR13** [ietf-scitt/draft-birkholz-scitt-architecture#25]
### Case 0 

- Public Read
- Private Write

### Case 1

- Private Read
- Private Write

When holding an endorsement, one might be be able to verify directly in a public read, or rely on an auditor in the case of a private read scenario.

**Comment by SteveLasker** [comment]
I'm struggling a bit with what it means to have anyone be able to write. While it sounds great, and makes a great demo, it leads to so many security, DOS issues, I question the value. 
Standard RBAC write/query/read makes sense.

**Comment by OR13** [comment]
> I'm struggling a bit with what it means to have anyone be able to write.

both scenarios have "private write", this implies some form of AuthZ.

**Comment by yogeshbdeshpande** [comment]
@SteveLasker to move this issue to new repo

**Comment by SteveLasker** [comment]
Closing, as this has been copied over to: https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/14
