### ISSUE TITLE
Considering the impact of claim semantics on policy layer

### ISSUE THREAD

**Issue by OR13** [ietf-scitt/draft-birkholz-scitt-architecture#26]
When specific and detailed claims are provided an advanced policy might be applied.

If only shallow / simple claims are provided, there is not much of an opportunity to apply advanced policies.

**Comment by yogeshbdeshpande** [comment]
@OR13: A very valid point. We have not investigated this in detail.

We will need to move this Architecture Repo

**Comment by yogeshbdeshpande** [comment]
@SteveLasker To move this issue to a new repo

**Comment by SteveLasker** [comment]
Closing as this has been copied over to: https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/12
