### ISSUE TITLE
Add a sequence diagram

### ISSUE THREAD

**Issue by OR13** [ietf-scitt/draft-birkholz-scitt-architecture#27]
##  Compound User Story / Sequence Diagram

As a consumer, I want to understand if I should trust an artifact
As a producer, I want to be assured that the integrity of my artifacts has been reviewed by a trusted 3rd party.

```mermaid
sequenceDiagram
    participant Issuer
    participant Notary
    Note left of Issuer: I take responsibility for the artifacts I produce
    Issuer ->> Notary: These are the policies I am committed to meeting
    Issuer ->> Notary: I stand by my claims about my artifact
    loop Claims Check
        Notary ->> Notary: Review relevant claims and policies
    end
    Notary ->> Issuer: Here is my endorsement and receipt
    Consumer->>Notary: Is this artifact safe to use?
    loop Endorsement Check
        Notary->>Notary: Review relevant claims and endorsements
    end
     Notary ->> Consumer: You can trust this artifact, the endorsement is still valid
     Note right of Consumer: I have confidence in the artifacts I consume
```

**Comment by johnandersen777** [comment]
- Mermaid docs for other unfamiliar contributors:
  - https://mermaid-js.github.io/mermaid/#/sequenceDiagram
  - https://mermaid-js.github.io/mermaid-live-editor/

**Comment by yogeshbdeshpande** [comment]
@SteveLasker Need to move this to new github repo

**Comment by SteveLasker** [comment]
Closing as this has been copied over to: https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/13
