### ISSUE TITLE
Replace TS with SCITT?

### ISSUE THREAD

**Issue by SteveLasker** [ietf-scitt/draft-birkholz-scitt-architecture#28]
Reading the architecture doc, I see TS, meant to refer to a Transparency Service. I keep reading this as Time Stamp service. 
Could/should we replace TS with SCITT, as that is the term we're using.

**Comment by SteveLasker** [comment]
We may also want to reconcile TS, SCITT with Registry, as worded. All three represent a SCITT instance. Should we consolidate the references as one?
- [ ] TS
- [ ] SCITT Instance
- [ ] Registry

**Comment by fournet** [comment]
I have a slight preference for TS, as we use SCITT for the whole architecture (not its transparency service) and Registry as the more general service that also deals with queries, storage, etc.

**Comment by yogeshbdeshpande** [comment]
@SteveLasker to close this issue:

**Comment by SteveLasker** [comment]
Closing as this is captured in: https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/8
