### ISSUE TITLE
Definitions & Terms: Change Statement to Evidence

### ISSUE THREAD

**Issue by SteveLasker** [ietf-scitt/draft-birkholz-scitt-architecture#29]
Under [Terminology](https://www.ietf.org/archive/id/draft-birkholz-scitt-architecture-01.html#name-terminology) we define:
> Statement:- any serializable information about an Artifact. To help interpretation of Statements, they must be tagged with a media type (as specified in [[RFC6838](https://www.ietf.org/archive/id/draft-birkholz-scitt-architecture-01.html#RFC6838)]). For example, a statement may represent a Software Bill Of Materials (SBOM) that lists the ingredients of a software Artifact, or some endorsement or attestation about an Artifact.

Haven't we been using Evidence as the term? Users submit claims, which have optional evidence to support the claim.

**Comment by letmaik** [comment]
Statement is the payload you sign. Evidence is extra material linked to from the statement (via hash etc.). Claim is a signed statement. That's my understanding.

**Comment by henkbirkholz** [comment]
In RATS, Evidence is:

> A set of Claims generated by an Attester to be appraised by a Verifier. Evidence may include configuration data, measurements, telemetry, or inferences.

For example, if an Issuer produces a Claim (in SCITT that overloaded term means a signed statement about a supply chain artifact), Evidence (or corresponding typically more concise Attestation Results) could be embedded in that Claim to increase trust in the trustworthiness of the Issuer.

Today, the SCITT architecture does not require inclusion of Evidence or Attestation Results in Claims.

For Transparent Claims that could already be part of SCITT after a first rechartering. We have to see how the initial works evolves in the WG, though.

**Comment by joshuagl** [comment]
FWIW (and I know the term attestation, especially, has a different meaning here due to RATS) we describe the model and terminology for an attestation in SLSA here https://slsa.dev/attestation-model#model-and-terminology

A `subject` describes the thing being attested to (or about which claims are being made).
A `predicate` is arbitrary metadata about the `subject`.
A `statement` binds a `subject` to a `predicate`.

**Comment by henkbirkholz** [comment]
That always left me curious: Was there a reason to reuse the knowledge-graph'esque terms originating from triples (subject, predicate, object) in a different manner? The expression that is a SLSA attestation seems to be a basis for graph building, too. Correspondingly, I never really understood the origin of using `subject`, `predicate`, and `statement` where statement is the "binding part" while in knowledge graphs predicate is the "binding part".

**Comment by yogeshbdeshpande** [comment]
@SteveLasker to Migrate this to new repo

**Comment by SteveLasker** [comment]
There are two issues captured here:
- https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/8
- https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/10
