### ISSUE TITLE
Add claim and receipt side by side in future revision

### ISSUE THREAD

**Issue by OR13** [ietf-scitt/draft-birkholz-scitt-architecture#32]
We discussed a future revision where claim and receipt are visualized next to each other.

https://github.com/ietf-scitt/draft-birkholz-scitt-architecture/pull/23/files#r1001967472

**Comment by yogeshbdeshpande** [comment]
@OR13 shall we close this issue now?

**Comment by SteveLasker** [comment]
Closing to leave the archived repo in a stable state. 
@OR13, please open under https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/new if you feel this isn't covered.
