### ISSUE TITLE
Clarify how a statement refers to other documents

### ISSUE THREAD

**Issue by SteveLasker** [ietf-scitt/draft-birkholz-scitt-architecture#33]
The current definition of a statement says:

> Statement:
any serializable information about an Artifact. To help interpretation of Statements, they must be tagged with a media type (as specified in [[RFC6838](https://ietf-scitt.github.io/draft-birkholz-scitt-architecture/draft-birkholz-scitt-architecture.html#RFC6838)]). For example, a statement may represent a Software Bill Of Materials (SBOM) that lists the ingredients of a software Artifact, or some endorsement or attestation about an Artifact.

The proposal is to assure the SBOM, as an example content that is being added to the registry, has a means to be stored outside the ledger, but verified by the ledger.
On submission to the ledger, the SBOM is referenced, but not directly embedded in the statement. This allows the registry to optionally index the content. A particular instance may put the content on the ledger, or store it alongside the ledger.

**Comment by yogeshbdeshpande** [comment]
@letmaik and @fournet will work on this!

**Comment by SteveLasker** [comment]
Closing as this is covered by https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/8 in the new repo.
