### ISSUE TITLE
Refine definition of feed

### ISSUE THREAD

**Issue by SteveLasker** [ietf-scitt/draft-birkholz-scitt-architecture#36]
A feed is a great base for how we can create a series of statements for different artifacts, getting freshness for a receipt/or VEX report.
The current definition likely needs to expand a bit to account for:
- What are the versions of a specific artifact
- What are all the statements for a version of an artifact
- What is the latest statement for a specific contentType of a specific versioned artifact: (eg: what's the latest VEX for the `net-monitor:v1` software?
- If the contentType is a referenced [statement by reference](#35), which stores SBOMs, VEX, Scan Reports, how do we drill into each if they all use the same payload contentType of satementByReference?

**Comment by yogeshbdeshpande** [comment]
@SteveLasker To move this to new repo with correct definition of the problem statement

**Comment by SteveLasker** [comment]
Closing as this has been copied over to: https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/11
