### ISSUE TITLE
RATS and SCITT

### ISSUE THREAD

**Issue by kkarunakaran89** [ietf-scitt/draft-birkholz-scitt-architecture#37]
We need documentation around SCITT and RATS focusing on how they interact, overlap and what specific problems they solve (use case documentation) 
Issue created for tracking

**Comment by yogeshbdeshpande** [comment]
| SCITT Terminology    | Definition                                                                                                                | RATS Terminology | Definition                                                                                                                                          | Similarity | Difference                                               |
|----------------------|---------------------------------------------------------------------------------------------------------------------------|------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------|------------|----------------------------------------------------------|
| Artifact             | a physical or non-physical item that is moving along the supply chain.                                                    | Artifact         | Any item produced or consumed by a RATs role                                                                                                        |            |                                                          |
| Statement            | any serializable information about an Artifact, example SBOM etc                                                          | Claim (UCCS)       |  A piece of asserted information, often in the form of a name/value pair.  |            |  |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
| Claim        | an identifiable and non-repudiable Statement about an Artifact made by an Issuer.   | Endorsement            |  An Endorsement in RATS is signed i.e. a secure statement                                                                          |             |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           | Evidence         | A set of claims generated by an Attester. Includes Measurement or Config Data                                                                       |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
| Registry             | Verifiable Append Only Data Structure                                                                                     |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
| Transparency Service |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |
|                      |                                                                                                                           |                  |                                                                                                                                                     |            |                                                          |

**Comment by yogeshbdeshpande** [comment]
| SCITT role name | Description                                                                                                                             | RATS Role Name | Description                                                                                                                                                   |   |   |
|-----------------|-----------------------------------------------------------------------------------------------------------------------------------------|----------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------|---|---|
| Issuer          | A role, that make claims about an artifact in supply chain                                                                              | Attester       | A role performed by en entity, typically a device whose Evidence must be appraosed to infer trustrworthiness                                                  |   |   |
|                 |                                                                                                                                         |                |                                                                                                                                                               |   |   |
| Endorser        |                                                                                                                                         | Endorser       | Entity that produces Endorsements that help Verifier appraise Evidence                                                                                        |   |   |
| Verifier        | An entity that consuumes transparent claims, verifying their proofs, i.e. presence in transparent registry and inspecting the statement | Verifier       |  an entity that appraises the validity of Evidence about an Attester and produces Attestation Results to be used by a Relying Party.                          |   |   |
|                 |                                                                                                                                         |                |                                                                                                                                                               |   |   |
| Auditor         |                                                                                                                                         |                |                                                                                                                                                               |   |   |
|                 |                                                                                                                                         |                |                                                                                                                                                               |   |   |
| Relying Party   | N/A                                                                                                                                     | Relying party  | A role performed by an entity that depends on the validity of information about an Attester, for purposes of reliably applying application specific actions.  |   |   |
|                 |                                                                                                                                         |                |                                                                                                                                                               |   |   |
|                 |                                                                                                                                         |                |                                                                                                                                                               |   |   |
|                 |                                                                                                                                         |                |                                                                                                                                                               |   |   |
|                 |                                                                                                                                         |                |                                                                                                                                                               |   |   |
|                 |                                                                                                                                         |                |                                                                                                                                                               |   |   |
|                 |                                                                                                                                         |                |                                                                                                                                                               |   |   |
|                 |                                                                                                                                         |                |                                                                                                                                                               |   |   |
|                 |                                                                                                                                         |                |                                                                                                                                                               |   |   |
|                 |                                                                                                                                         |                |                                                                                                                                                               |   |   |
|                 |                                                                                                                                         |                |                                                                                                                                                               |   |   |
|                 |                                                                                                                                         |                |                                                                                                                                                               |   |   |
|                 |                                                                                                                                         |                |                                                                                                                                                               |   |   |
|                 |                                                                                                                                         |                |                                                                                                                                                               |   |   |

**Comment by fournet** [comment]
Claim is a clear clash, as in RATS's claim would be components in the payload or headers of of SCITT's claims. We could document it, or find a synonym for SCITT. I think it is important to keep separating SCITT's statement and SCITT claim, the former referring to the opaque payload of the latter. RATS's distinction between *relying party* and their trusted delegate *verifier* is fine, but could be kept implicit in SCITT.

**Comment by fournet** [comment]
(For what it is worth, I am puzzled by the use of "claim" in RATS, which in my opinion deviates from its use e.g. in modal logic or authorization logic.)

**Comment by yogeshbdeshpande** [comment]
We had a productive discussion about this issue on Thursday 24th November 2022. Here is a proposal (nothing has been finalized yet) so just pondered over few possibilities which are listed below:

1) Every one agreed that there is a clear clash of term `claims` between RATS and SCITT.
Team debated on various other alternatives like :
(a) Calling always a Claim in SCITT as SCITT claim. However this option was ruled out as in IETF the WG name is not allowed as terms for entities/roles.

(b) Calling SCITT usage of claim as "signed claim". This is better as SCITT never has any possibility of an unsigned claim, so this is a best possible option to avoid the confusion with RATS.

(c) Use "signed statement" to refer to a SCITT claim. This usage is not a prefferred option  as not any signed statement is equivalent to a claim in SCITT. The signing has a specific signer associated within SCITT, especially a signing by an issuer is only an acceptable claim.  Hence this option is rejected.

2) Clear clash in the Role Name : "Verifier".

Verifier in SCITT is actually a shallow verification which only verifies the presence of Claim/Claims in a SCITT registry.
However it does not ascertain the complete "truthfulness" of claims. This is a role that needs further delegation to an issuer beyond a SCITT boundaries.

Possible option is to rename SCITT Verifier to Relying Party. However few think that this is too high level as Relying Party often delegates the verification responsibility to another entity.

Team decided to ponder for more options to a suitable name close to "Verification" but does not overlap with RATS terminology.

**Comment by yogeshbdeshpande** [comment]
@yogeshbdeshpande to move this issue to new repo: Create a proposal

**Comment by SteveLasker** [comment]
Closing as this should be covered by" https://github.com/ietf-scitt/draft-birkholz-scitt-architecture/issues/37
