### ISSUE TITLE
Registry & Transparency Service

### ISSUE THREAD

**Issue by SteveLasker** [ietf-scitt/draft-birkholz-scitt-architecture#38]
The architecture I-D, and other docs use Registry and Transparency Service (TS) interchangeably. 

This issue is about consistent naming, and what we should use for an implementation that hosts the SCITT standards.  
As we've discussed various terms, I'm pasting a "thousand words" to highlight conceptual components.

![image](https://user-images.githubusercontent.com/7647382/202588667-782e7227-ac9b-49f5-b740-0a2a27fd807d.png)

How do we finish this sentence:  
*The user will submit a signed statement/claim (see issue #34) to the ___*

1. The thing we're trying to name here, which is an implementation of a service.
2. The **eNotary** component that evaluates the Registration Policy (3) before proceeding
3. The **Registration Policy**, as the gatekeeper for what may be submitted to the ledger.
4. The **eNotary** counter signing key/service
5. The **ledger**, where statements/claims are persisted
6. The ledger of a ___ (1) may be implemented through various "ledger databases", such as [Azure CCF](https://azure.microsoft.com/en-us/products/azure-confidential-ledger/), [QLDB](https://aws.amazon.com/qldb/), [Trillian](https://github.com/google/trillian)

This issue is to discuss what we call (1)
Please "vote" with a comment, representing a number, and any supporting thoughts:

1. Transparency Service (with no acronym)
2. Registry
3. SCITT Implementation
4. Transparency Service (TS as a acronym)
5. _write in your own_

**Comment by letmaik** [comment]
Transparency Service.

Why: It's much less confusing than "registry" which is used in lots of other contexts already.

Side note: The functionality of eNotary and ledger is sometimes combined (e.g., CCF), and sometimes separate (e.g., Trillian and its personalities).

**Comment by rjb4standards** [comment]
+1 for Transparency Service

**Comment by SteveLasker** [comment]
Sorry, one more clarification. 
Should we be using TS as an acronym, or expand out. It's just text :)
I've added an additional (4)

**Comment by rjb4standards** [comment]
TS acronym is not offensive to me. Either way is ok with me.

**Comment by kaywilliams** [comment]
I have a preference for expanding out ('Transparency Service') in the general case, and abbreviating as an exception under extreme space constraints (e.g. small box in a diagram).

**Comment by yogeshbdeshpande** [comment]
@SteveLasker We need to move this to new repo

**Comment by SteveLasker** [comment]
Closing as this has been copied over to: https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/7
