### ISSUE TITLE
Change term 'artifact'

### ISSUE THREAD

**Issue by kaywilliams** [ietf-scitt/draft-birkholz-scitt-architecture#42]
The architecture document currently defines 'artifact' as the 'physical or non-physical item that is moving along the supply chain'. In other forums, different terms are used, for example: 'supplied good', 'product', 'asset'.

**Comment by joshuagl** [comment]
FWIW in in-toto attestations (as recommended by SLSA) we refer to the `subject` of an attestation. See https://github.com/in-toto/attestation/blob/main/spec/README.md#statement

**Comment by kaywilliams** [comment]
+1 for the generic term 'subject'.

**Comment by henkbirkholz** [comment]
Both `subject` and `object` where also terms that stakeholders from the HW supply chain could get behind at, IIRC. Have to cehck after MLKday.

**Comment by yogeshbdeshpande** [comment]
@SteveLasker We will move this new repository:

**Comment by SteveLasker** [comment]
Closing as this has been copied over to: https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/9
