### ISSUE TITLE
Archiving as IETF adopted SCITT under a working group

### ISSUE THREAD

**Issue by SteveLasker** [ietf-scitt/draft-birkholz-scitt-architecture#45]
Tracking the freezing this repo, (with the archive flag) as this work has moved to [draft-ietf-scitt-architecture](https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture)

**Comment by letmaik** [comment]
To avoid confusion, I suggest disabling the GitHub pages publication, removing the links from the README, and adding a link to the new repository.

**Comment by SteveLasker** [comment]
Closing as we've now copied over all issues to https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/
